---
- name: Extract artifact
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/
- name: Start the app
    shell: |
      npm install
      cd /home/ubuntu/backend
      pm2 stop default
      pm2 start npm -- start